apiVersion: v1
kind: Pod
metadata:
  name: web1
  labes:
    type: web1
spec:
  nodeSelector:
    a-team: '1'
  containers:
  - name: container 
    image: kubetm/app
  terminationGracePeriodSeconds: 0