apiVersion: v1
kind: Pod
metadata:
 name: pod1-with-no-execute
spec:
  tolerations:
    - effect: NoExecute
      key: out-of-disk
      operator: Exists
      tolerationSeconds: 30
  containers:
  - name: container
    image: kubetm/app
  terminationGracePeriodSeconds: 0 