apiVersion: v1
kind: Service
metadata:
  name: svc-2
spec:
  selector:
    app: pod
  ports:
  - port: 9000 # Cluster IP (Internal Service Port)
    targetPort: 8080 #(Internal Pod Container Port)
    nodePort: 30001 #(External Cluster IP)
  type: NodePort 
  externalTrafficPolicy: Local