apiVersion: v1
kind: LimitRange
metadata:
  name: lr-1
spec:
  limits:
  - type: Container
  min: 
    memory: 0.1Gi
  max:
    memory: 0.4GI
  maxLimitRequestRatio:
    memory: 3
  defaultRequest:
    memory: 0.1Gi
  default:
    memory: 0.2Gi
