apiVersion: v1
kind: Service
metadata: 
  name: loadbalancer-practice
  labels: 
    app: my-app
spec: 
  type: LoadBalancer
  selector: 
    app: my-app
  ports: 
    - port: 80
      targetPort: 8080